# Generated by Django 3.2 on 2023-04-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuboidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='creator',
            new_name='created_by',
        ),
    ]
