# Generated by Django 3.2 on 2023-04-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuboidapp', '0002_rename_creator_box_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
